// Generated by frontend/scripts/generate-music-registry.mjs. Do not edit by hand.
import type { AudioRegistryEntry } from './AudioTypes';

export const GENERATED_MUSIC_DIRECTORY_TRACKS: AudioRegistryEntry[] = [
  {
    "id": "music.opening_theme",
    "label": "Opening Theme",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/1-01.%20Opening%20Theme.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.1200_am_sunny",
    "label": "1200 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/1-02.%201200%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.subwoofer_lullaby",
    "label": "Subwoofer Lullaby",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/1-03.%20Subwoofer%20Lullaby.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.minecraft_haggstrom",
    "label": "Minecraft Haggstrom",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/1-04.%20minecraft-%20Haggstrom.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.600_pm_rainy",
    "label": "600 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/2-19.%20600%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.its_decided_then",
    "label": "It's Decided Then",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/011%20-%20It%27s%20Decided%20Then.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.zen_garden_in_game",
    "label": "Zen Garden IN GAME",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/23.%20Zen%20Garden%20IN-GAME.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.nookingtons_closing_time",
    "label": "Nookington's (Closing Time)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/043%20-%20Nookington%27s%20(Closing%20Time).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_01_opening_theme",
    "label": "Opening Theme",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-01.%20Opening%20Theme.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_02_1200_am_sunny",
    "label": "1200 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-02.%201200%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_03_100_am_sunny",
    "label": "100 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-03.%20100%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_04_200_am_sunny",
    "label": "200 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-04.%20200%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_05_300_am_sunny",
    "label": "300 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-05.%20300%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_06_400_am_sunny",
    "label": "400 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-06.%20400%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_07_500_am_sunny",
    "label": "500 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-07.%20500%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_08_600_am_sunny",
    "label": "600 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-08.%20600%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_09_700_am_sunny",
    "label": "700 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-09.%20700%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_10_800_am_sunny",
    "label": "800 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-10.%20800%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_11_900_am_sunny",
    "label": "900 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-11.%20900%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_12_1000_am_sunny",
    "label": "1000 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-12.%201000%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_13_1100_am_sunny",
    "label": "1100 AM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-13.%201100%20AM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_14_1200_pm_sunny",
    "label": "1200 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-14.%201200%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_15_100_pm_sunny",
    "label": "100 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-15.%20100%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_16_200_pm_sunny",
    "label": "200 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-16.%20200%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_17_300_pm_sunny",
    "label": "300 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-17.%20300%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_18_400_pm_sunny",
    "label": "400 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-18.%20400%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_19_500_pm_sunny",
    "label": "500 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-19.%20500%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_20_600_pm_sunny",
    "label": "600 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-20.%20600%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_21_700_pm_sunny",
    "label": "700 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-21.%20700%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_22_800_pm_sunny",
    "label": "800 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-22.%20800%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_23_900_pm_sunny",
    "label": "900 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-23.%20900%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_24_1000_pm_sunny",
    "label": "1000 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-24.%201000%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_1_25_1100_pm_sunny",
    "label": "1100 PM (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/1-25.%201100%20PM%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_01_1200_am_rainy",
    "label": "1200 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-01.%201200%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_02_100_am_rainy",
    "label": "100 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-02.%20100%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_03_200_am_rainy",
    "label": "200 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-03.%20200%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_04_300_am_rainy",
    "label": "300 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-04.%20300%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_05_400_am_rainy",
    "label": "400 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-05.%20400%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_06_500_am_rainy",
    "label": "500 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-06.%20500%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_07_600_am_rainy",
    "label": "600 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-07.%20600%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_08_700_am_rainy",
    "label": "700 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-08.%20700%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_09_800_am_rainy",
    "label": "800 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-09.%20800%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_10_900_am_rainy",
    "label": "900 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-10.%20900%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_11_1000_am_rainy",
    "label": "1000 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-11.%201000%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_12_1100_am_rainy",
    "label": "1100 AM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-12.%201100%20AM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_13_1200_pm_rainy",
    "label": "1200 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-13.%201200%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_14_100_pm_rainy",
    "label": "100 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-14.%20100%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_15_200_pm_rainy",
    "label": "200 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-15.%20200%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_16_300_pm_rainy",
    "label": "300 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-16.%20300%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_17_400_pm_rainy",
    "label": "400 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-17.%20400%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_18_500_pm_rainy",
    "label": "500 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-18.%20500%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_19_600_pm_rainy",
    "label": "600 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-19.%20600%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_20_700_pm_rainy",
    "label": "700 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-20.%20700%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_21_800_pm_rainy",
    "label": "800 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-21.%20800%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_22_900_pm_rainy",
    "label": "900 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-22.%20900%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_23_1000_pm_rainy",
    "label": "1000 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-23.%201000%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_24_1100_pm_rainy",
    "label": "1100 PM (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-24.%201100%20PM%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_25_1200_am_snowy",
    "label": "1200 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-25.%201200%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_26_100_am_snowy",
    "label": "100 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-26.%20100%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_27_200_am_snowy",
    "label": "200 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-27.%20200%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_28_300_am_snowy",
    "label": "300 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-28.%20300%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_29_400_am_snowy",
    "label": "400 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-29.%20400%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_30_500_am_snowy",
    "label": "500 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-30.%20500%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_31_600_am_snowy",
    "label": "600 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-31.%20600%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_32_700_am_snowy",
    "label": "700 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-32.%20700%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_33_800_am_snowy",
    "label": "800 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-33.%20800%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_34_900_am_snowy",
    "label": "900 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-34.%20900%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_35_1000_am_snowy",
    "label": "1000 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-35.%201000%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_36_1100_am_snowy",
    "label": "1100 AM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-36.%201100%20AM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_37_1200_pm_snowy",
    "label": "1200 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-37.%201200%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_38_100_pm_snowy",
    "label": "100 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-38.%20100%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_39_200_pm_snowy",
    "label": "200 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-39.%20200%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_40_300_pm_snowy",
    "label": "300 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-40.%20300%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_41_400_pm_snowy",
    "label": "400 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-41.%20400%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_42_500_pm_snowy",
    "label": "500 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-42.%20500%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_43_600_pm_snowy",
    "label": "600 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-43.%20600%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_44_700_pm_snowy",
    "label": "700 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-44.%20700%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_45_800_pm_snowy",
    "label": "800 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-45.%20800%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_46_900_pm_snowy",
    "label": "900 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-46.%20900%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_47_1000_pm_snowy",
    "label": "1000 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-47.%201000%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_2_48_1100_pm_snowy",
    "label": "1100 PM (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/2-48.%201100%20PM%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_01_resident_services_tent",
    "label": "Resident Services (Tent)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-01.%20Resident%20Services%20(Tent).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_02_resident_services",
    "label": "Resident Services",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-02.%20Resident%20Services.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_03_blathers_tent",
    "label": "Blathers' Tent",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-03.%20Blathers%27%20Tent.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_04_museum_entrance",
    "label": "Museum (Entrance)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-04.%20Museum%20(Entrance).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_05_museum_fish_room",
    "label": "Museum (Fish Room)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-05.%20Museum%20(Fish%20Room).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_06_museum_insect_room",
    "label": "Museum (Insect Room)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-06.%20Museum%20(Insect%20Room).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_07_museum_fossil_room",
    "label": "Museum (Fossil Room)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-07.%20Museum%20(Fossil%20Room).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_08_museum_art_room",
    "label": "Museum (Art Room)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-08.%20Museum%20(Art%20Room).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_09_airport_lobby_speaker_version",
    "label": "Airport Lobby (Speaker Version)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-09.%20Airport%20Lobby%20(Speaker%20Version).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_10_airport_lobby_full_sound_version",
    "label": "Airport Lobby (Full Sound Version)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-10.%20Airport%20Lobby%20(Full%20Sound%20Version).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_11_able_sisters",
    "label": "Able Sisters",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-11.%20Able%20Sisters.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_12_nooks_cranny_small",
    "label": "Nook's Cranny (Small)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-12.%20Nook%27s%20Cranny%20(Small).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_13_nooks_cranny_big",
    "label": "Nook's Cranny (Big)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-13.%20Nook%27s%20Cranny%20(Big).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_14_nooks_cranny_before_closing",
    "label": "Nook's Cranny (Before Closing)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-14.%20Nook%27s%20Cranny%20(Before%20Closing).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_15_jolly_redds_treasure_trawler",
    "label": "Jolly Redd's Treasure Trawler",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-15.%20Jolly%20Redd%27s%20Treasure%20Trawler.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_16_dreaming",
    "label": "Dreaming",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-16.%20Dreaming.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_17_island_life_orientation_1",
    "label": "Island Life Orientation 1",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-17.%20Island%20Life%20Orientation%201.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_18_island_life_orientation_2",
    "label": "Island Life Orientation 2",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-18.%20Island%20Life%20Orientation%202.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_19_island_life_orientation_3",
    "label": "Island Life Orientation 3",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-19.%20Island%20Life%20Orientation%203.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_20_island_life_orientation_4_campfire_evening",
    "label": "Island Life Orientation 4 (Campfire Evening)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-20.%20Island%20Life%20Orientation%204%20(Campfire%20Evening).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_21_island_life_orientation_5_sunny",
    "label": "Island Life Orientation 5 (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-21.%20Island%20Life%20Orientation%205%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_22_island_life_orientation_5_rainy",
    "label": "Island Life Orientation 5 (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-22.%20Island%20Life%20Orientation%205%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_23_island_life_orientation_5_snowy",
    "label": "Island Life Orientation 5 (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-23.%20Island%20Life%20Orientation%205%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_24_island_life_orientation_6_sunny",
    "label": "Island Life Orientation 6 (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-24.%20Island%20Life%20Orientation%206%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_25_island_life_orientation_6_rainy",
    "label": "Island Life Orientation 6 (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-25.%20Island%20Life%20Orientation%206%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_26_island_life_orientation_6_snowy",
    "label": "Island Life Orientation 6 (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-26.%20Island%20Life%20Orientation%206%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_27_island_life_orientation_7_sunny",
    "label": "Island Life Orientation 7 (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-27.%20Island%20Life%20Orientation%207%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_28_island_life_orientation_7_rainy",
    "label": "Island Life Orientation 7 (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-28.%20Island%20Life%20Orientation%207%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_29_island_life_orientation_7_snowy",
    "label": "Island Life Orientation 7 (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-29.%20Island%20Life%20Orientation%207%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_30_mystery_island_tour_noon_sunny",
    "label": "Mystery Island Tour Noon (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-30.%20Mystery%20Island%20Tour%20Noon%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_31_mystery_island_tour_noon_rainy",
    "label": "Mystery Island Tour Noon (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-31.%20Mystery%20Island%20Tour%20Noon%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_32_mystery_island_tour_noon_snowy",
    "label": "Mystery Island Tour Noon (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-32.%20Mystery%20Island%20Tour%20Noon%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_33_mystery_island_tour_evening_sunny",
    "label": "Mystery Island Tour Evening (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-33.%20Mystery%20Island%20Tour%20Evening%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_34_mystery_island_tour_evening_rainy",
    "label": "Mystery Island Tour Evening (Rainy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-34.%20Mystery%20Island%20Tour%20Evening%20(Rainy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_3_35_mystery_island_tour_evening_snowy",
    "label": "Mystery Island Tour Evening (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/3-35.%20Mystery%20Island%20Tour%20Evening%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_01_tournament_in_progress",
    "label": "Tournament (In Progress)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-01.%20Tournament%20(In%20Progress).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_02_tournament_joining",
    "label": "Tournament (Joining)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-02.%20Tournament%20(Joining).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_03_bunny_day",
    "label": "Bunny Day",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-03.%20Bunny%20Day.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_04_wedding_season_reese_and_cyrus",
    "label": "Wedding Season (Reese & Cyrus)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-04.%20Wedding%20Season%20(Reese%20%26%20Cyrus).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_05_wedding_season_party",
    "label": "Wedding Season (Party)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-05.%20Wedding%20Season%20(Party).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_06_fireworks_show",
    "label": "Fireworks Show",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-06.%20Fireworks%20Show.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_07_halloween",
    "label": "Halloween",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-07.%20Halloween.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_08_turkey_day",
    "label": "Turkey Day",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-08.%20Turkey%20Day.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_09_turkey_day_cooking_start",
    "label": "Turkey Day (Cooking Start)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-09.%20Turkey%20Day%20(Cooking%20Start).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_10_turkey_day_cooking_complete",
    "label": "Turkey Day (Cooking Complete)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-10.%20Turkey%20Day%20(Cooking%20Complete).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_11_toy_day_snowy",
    "label": "Toy Day (Snowy)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-11.%20Toy%20Day%20(Snowy).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_12_toy_day_sunny",
    "label": "Toy Day (Sunny)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-12.%20Toy%20Day%20(Sunny).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_13_countdown_1100_pm",
    "label": "Countdown (1100 PM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-13.%20Countdown%20(1100%20PM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_14_countdown_1130_pm",
    "label": "Countdown (1130 PM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-14.%20Countdown%20(1130%20PM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_15_countdown_1150_pm",
    "label": "Countdown (1150 PM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-15.%20Countdown%20(1150%20PM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_16_countdown_1155_pm",
    "label": "Countdown (1155 PM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-16.%20Countdown%20(1155%20PM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_17_new_year_happy_new_year",
    "label": "New Year (Happy New Year)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-17.%20New%20Year%20(Happy%20New%20Year).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_18_new_year_1200_am",
    "label": "New Year (1200 AM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-18.%20New%20Year%20(1200%20AM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_19_new_year_200_am",
    "label": "New Year (200 AM)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-19.%20New%20Year%20(200%20AM).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_20_new_years_day",
    "label": "New Year's Day",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-20.%20New%20Year%27s%20Day.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_21_festivale",
    "label": "Festivale",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-21.%20Festivale.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_22_festivale_kimedance_normal",
    "label": "Festivale Kimedance (Normal)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-22.%20Festivale%20Kimedance%20(Normal).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_23_festivale_kimedance_complete",
    "label": "Festivale Kimedance (Complete)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-23.%20Festivale%20Kimedance%20(Complete).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_24_nook_inc_deserted_island_getaway_package_check_in_counter",
    "label": "Nook Inc. Deserted Island Getaway Package Check In Counter",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-24.%20Nook%20Inc.%20Deserted%20Island%20Getaway%20Package%20Check-in%20Counter.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_25_k_k_slider_dream",
    "label": "K.K. Slider Dream",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-25.%20K.K.%20Slider%20Dream.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_26_island_broadcast_tom_nook",
    "label": "Island Broadcast (Tom Nook)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-26.%20Island%20Broadcast%20(Tom%20Nook).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_27_island_broadcast_isabelle",
    "label": "Island Broadcast (Isabelle)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-27.%20Island%20Broadcast%20(Isabelle).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_28_facility_completion_ceremony",
    "label": "Facility Completion Ceremony",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-28.%20Facility%20Completion%20Ceremony.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_29_outing_dal_fanfare",
    "label": "Outing (DAL Fanfare)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-29.%20Outing%20(DAL%20Fanfare).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_30_outing_in_flight_broadcast",
    "label": "Outing (In Flight Broadcast)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-30.%20Outing%20(In-Flight%20Broadcast).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_31_outing_waiting",
    "label": "Outing (Waiting)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-31.%20Outing%20(Waiting).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_32_outing_meeting",
    "label": "Outing (Meeting)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-32.%20Outing%20(Meeting).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_33_outing_farewell",
    "label": "Outing (Farewell)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-33.%20Outing%20(Farewell).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_34_rescue_service",
    "label": "Rescue Service",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-34.%20Rescue%20Service.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_35_amiibo_invitation",
    "label": "Amiibo Invitation",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-35.%20amiibo%20Invitation.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_36_chased_by_bee",
    "label": "Chased By Bee",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-36.%20Chased%20by%20Bee.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_37_stung_by_bee",
    "label": "Stung By Bee",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-37.%20Stung%20by%20Bee.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_38_stung_by_scorpiontarantula",
    "label": "Stung By ScorpionTarantula",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-38.%20Stung%20by%20ScorpionTarantula.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_39_get_fanfare",
    "label": "Get Fanfare",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-39.%20Get%20Fanfare.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_40_complete_fanfare",
    "label": "Complete Fanfare",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-40.%20Complete%20Fanfare.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_41_radio_jingle_morning_1",
    "label": "Radio Jingle (Morning 1)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-41.%20Radio%20Jingle%20(Morning%201).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_42_radio_jingle_morning_2",
    "label": "Radio Jingle (Morning 2)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-42.%20Radio%20Jingle%20(Morning%202).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_43_radio_jingle_morning_3",
    "label": "Radio Jingle (Morning 3)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-43.%20Radio%20Jingle%20(Morning%203).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_44_radio_jingle_morning_4",
    "label": "Radio Jingle (Morning 4)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-44.%20Radio%20Jingle%20(Morning%204).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_45_radio_jingle_morning_5",
    "label": "Radio Jingle (Morning 5)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-45.%20Radio%20Jingle%20(Morning%205).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_46_radio_jingle_morning_6",
    "label": "Radio Jingle (Morning 6)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-46.%20Radio%20Jingle%20(Morning%206).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_47_radio_jingle_noon_1",
    "label": "Radio Jingle (Noon 1)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-47.%20Radio%20Jingle%20(Noon%201).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_48_radio_jingle_noon_2",
    "label": "Radio Jingle (Noon 2)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-48.%20Radio%20Jingle%20(Noon%202).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_49_radio_jingle_noon_3",
    "label": "Radio Jingle (Noon 3)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-49.%20Radio%20Jingle%20(Noon%203).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_50_radio_jingle_noon_4",
    "label": "Radio Jingle (Noon 4)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-50.%20Radio%20Jingle%20(Noon%204).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_51_radio_jingle_noon_5",
    "label": "Radio Jingle (Noon 5)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-51.%20Radio%20Jingle%20(Noon%205).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_52_radio_jingle_noon_6",
    "label": "Radio Jingle (Noon 6)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-52.%20Radio%20Jingle%20(Noon%206).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_53_radio_jingle_evening_1",
    "label": "Radio Jingle (Evening 1)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-53.%20Radio%20Jingle%20(Evening%201).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_54_radio_jingle_evening_2",
    "label": "Radio Jingle (Evening 2)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-54.%20Radio%20Jingle%20(Evening%202).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_55_radio_jingle_evening_3",
    "label": "Radio Jingle (Evening 3)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-55.%20Radio%20Jingle%20(Evening%203).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_56_radio_jingle_evening_4",
    "label": "Radio Jingle (Evening 4)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-56.%20Radio%20Jingle%20(Evening%204).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_57_radio_jingle_evening_5",
    "label": "Radio Jingle (Evening 5)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-57.%20Radio%20Jingle%20(Evening%205).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_58_radio_jingle_evening_6",
    "label": "Radio Jingle (Evening 6)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-58.%20Radio%20Jingle%20(Evening%206).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_59_radio_jingle_bunny_day",
    "label": "Radio Jingle (Bunny Day)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-59.%20Radio%20Jingle%20(Bunny%20Day).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_60_radio_jingle_halloween",
    "label": "Radio Jingle (Halloween)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-60.%20Radio%20Jingle%20(Halloween).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_61_radio_jingle_turkey_day",
    "label": "Radio Jingle (Turkey Day)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-61.%20Radio%20Jingle%20(Turkey%20Day).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_62_radio_jingle_toy_day",
    "label": "Radio Jingle (Toy Day)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-62.%20Radio%20Jingle%20(Toy%20Day).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_63_radio_jingle_countdown",
    "label": "Radio Jingle (Countdown)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-63.%20Radio%20Jingle%20(Countdown).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_64_radio_jingle_carnival",
    "label": "Radio Jingle (Carnival)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-64.%20Radio%20Jingle%20(Carnival).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.animal_crossing_new_horizons_2021_4_65_opening_theme_remote_performance",
    "label": "Opening Theme (Remote Performance)",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Animal%20Crossing%20New%20Horizons%20(2021)/4-65.%20Opening%20Theme%20(Remote%20Performance).mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.grandpas_theme",
    "label": "Grandpa's Theme",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Grandpa%27s%20Theme.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  },
  {
    "id": "music.travelers",
    "label": "Travelers",
    "channel": "music",
    "source": {
      "kind": "relative",
      "path": "/music/Travelers.mp3"
    },
    "preload": true,
    "loop": false,
    "volume": 0.62,
    "tags": [
      "music",
      "playlist"
    ],
    "notes": "Generated playlist track from frontend/public/music."
  }
];
