import {
  basicPlantsUrl,
  chestUrl,
  eggNestUrl,
  fence03Url as fenceIconUrl,
  flashlightUrl,
  furnitureUrl,
  greenhouseCloseUrl,
  greenhouseStep0Url,
  greenhouseStep1Url,
  greenhouseStep2Url,
  greenhouseStep3Url,
  greenhouseStep4Url,
  houseKeyUrl,
  objectsUrl,
  pathsUrl,
  signsSidesUrl,
  stoneGolemPartUrl,
  stoneGolemWakeupUrl,
  toolsUrl,
} from '../../../../../assets';

export const GameVisualAssets = {
  toolsUrl,
  basicPlantsUrl,
  objectsUrl,
  furnitureUrl,
  eggNestUrl,
  greenhouseStep0Url,
  greenhouseStep1Url,
  greenhouseStep2Url,
  greenhouseStep3Url,
  greenhouseStep4Url,
  greenhouseCloseUrl,
  houseKeyUrl,
  flashlightUrl,
  fenceIconUrl,
  pathsUrl,
  signsSidesUrl,
  chestUrl,
  stoneGolemPartUrl,
  stoneGolemWakeupUrl,
};
